In [31]:
import numpy as np
import pandas as pd
from numpy.random  import randn
np.random.seed(123)

In [32]:
url = ('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv')

In [33]:
df = pd.read_csv(url)
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [34]:
## understand the data first (head, describe, etc.)

df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [36]:
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [37]:
# clean the dataset by naming the missing column name

df = df.rename(columns={'Unnamed: 0': 'Vehicle'})

df.columns

Index(['Vehicle', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [38]:
## create a new dataframe that consists of a subset of the original columns (only mpg, hp, wt, and cyl)

df[['mpg','hp','wt','cyl']]

     mpg   hp     wt  cyl
0   21.0  110  2.620    6
1   21.0  110  2.875    6
2   22.8   93  2.320    4
3   21.4  110  3.215    6
4   18.7  175  3.440    8
5   18.1  105  3.460    6
6   14.3  245  3.570    8
7   24.4   62  3.190    4
8   22.8   95  3.150    4
9   19.2  123  3.440    6
10  17.8  123  3.440    6
11  16.4  180  4.070    8
12  17.3  180  3.730    8
13  15.2  180  3.780    8
14  10.4  205  5.250    8
15  10.4  215  5.424    8
16  14.7  230  5.345    8
17  32.4   66  2.200    4
18  30.4   52  1.615    4
19  33.9   65  1.835    4
20  21.5   97  2.465    4
21  15.5  150  3.520    8
22  15.2  150  3.435    8
23  13.3  245  3.840    8
24  19.2  175  3.845    8
25  27.3   66  1.935    4
26  26.0   91  2.140    4
27  30.4  113  1.513    4
28  15.8  264  3.170    8
29  19.7  175  2.770    6
30  15.0  335  3.570    8
31  21.4  109  2.780    4

In [13]:
# rename the above columns (cylinders = cyl)

df = df.rename(columns={'cyl': 'cylinders'})

df.columns

Index(['Vehicle', 'mpg', 'cylinders', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [20]:
## summary statistics for those columns (average mpg)

df['mpg'].mean()

np.float64(20.090625000000003)

In [27]:
## filter your data and find summary statistics for only one type of vehicle

honda_civic = df[df['Vehicle'] == 'Honda Civic']
honda_civic.describe()

        mpg  cylinders  disp    hp  drat     wt   qsec   vs   am  gear  carb
count   1.0        1.0   1.0   1.0  1.00  1.000   1.00  1.0  1.0   1.0   1.0
mean   30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
std     NaN        NaN   NaN   NaN   NaN    NaN    NaN  NaN  NaN   NaN   NaN
min    30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
25%    30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
50%    30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
75%    30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
max    30.4        4.0  75.7  52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0